services:
  daca_catalog:
    url: http://daca-catalog-api:8001
  daca_catalog_status:
    url: http://daca-catalog-api:8001/api/v1/internal/opa
    credentials:
      bearer:
        token: local-development-only

bundles:
  daca:
    service: daca_catalog
    resource: api/v1/opa/bundles/catalog.tar.gz
    polling:
      min_delay_seconds: 2
      max_delay_seconds: 5

decision_logs:
  console: true

status:
  service: daca_catalog_status
