import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { StatusBadgeComponent } from '@bit-daca/design-system';
import { MappingDraftFacade } from './mapping-draft.facade';
import { DriftChange } from './data-models.models';

@Component({
  selector: 'daca-mapping-drift', standalone: true, imports: [StatusBadgeComponent], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="drift-view" aria-labelledby="drift-title"><header><div><p class="daca-eyebrow">Automatischer Snapshotvergleich</p><h2 id="drift-title">Drift prüfen und fachlich auflösen</h2><p>Technische Änderungen werden automatisch erkannt; Umbenennungen werden niemals stillschweigend bestätigt.</p></div><daca-status-badge [tone]="changes().length?'orange':'green'">{{ changes().length?changes().length+' Änderungen':'Keine Drift' }}</daca-status-badge></header>
      @if(changes().length){<div class="drift-list">@for(change of changes();track change.id){<article [class.is-breaking]="change.severity==='breaking'"><div class="drift-status"><strong>{{ severityLabel(change) }}</strong><span>{{ kindLabel(change.kind) }}</span></div><div><h3>{{ change.tableName }}{{ change.columnName?'.'+change.columnName:'' }}</h3><p>{{ changeDescription(change) }}</p>@if(change.impactedMappingIds.length||change.impactedLogicalFieldIds.length){<ul><li>{{ change.impactedMappingIds.length }} betroffene Zuordnung(en)</li><li>{{ change.impactedLogicalFieldIds.length }} betroffene logische Felder</li></ul>}</div><div class="drift-actions">@if(change.kind==='rename_candidate'){<daca-status-badge tone="orange">Kandidat · {{ confidenceLabel(change.confidence) }}</daca-status-badge>}@else{<daca-status-badge [tone]="change.severity==='breaking'?'red':'orange'">{{ change.resolved?'Aufgelöst':'Offen' }}</daca-status-badge>}@if(!change.resolved&&brokenMappingId(change);as mappingId){<button class="daca-button is-secondary" type="button" (click)="facade.openBrokenResolution(mappingId,$event.currentTarget)">Zuordnung auflösen</button>}</div></article>}</div>}@else{<div class="drift-empty"><h3>Snapshot ist kompatibel</h3><p>Es wurden keine strukturellen Änderungen gegenüber dem Vorgänger erkannt.</p></div>}
    </section>
  `,
  styles: [`
    .drift-view>header{display:flex;align-items:start;justify-content:space-between;gap:1rem;margin-bottom:1rem}.drift-view h2{margin:0;font-size:1.1rem}.drift-view header p:last-child{margin:.35rem 0 0;color:var(--daca-muted);font-size:.72rem}.drift-list{display:grid;gap:.7rem}.drift-list article{display:grid;grid-template-columns:110px minmax(0,1fr) auto;align-items:center;gap:1rem;border:1px solid var(--daca-border);border-left:5px solid var(--daca-orange);padding:1rem;background:#fff}.drift-list article.is-breaking{border-left-color:var(--daca-red)}.drift-status{display:grid;gap:.2rem}.drift-status strong{color:var(--daca-orange);font-size:.66rem;text-transform:uppercase}.is-breaking .drift-status strong{color:var(--daca-red-dark)}.drift-status span{font-size:.65rem}.drift-list h3,.drift-list p{margin:0}.drift-list h3{font-size:.84rem}.drift-list p{margin-top:.25rem;color:var(--daca-muted);font-size:.7rem}.drift-list ul{display:flex;flex-wrap:wrap;gap:.4rem;margin:.6rem 0 0;padding:0;list-style:none}.drift-list li{border:1px solid var(--daca-border);padding:.2rem .4rem;font-size:.6rem}.drift-actions{display:grid;justify-items:end;gap:.5rem}.drift-actions .daca-button{min-height:40px;white-space:nowrap}.drift-empty{border-left:5px solid var(--daca-green);padding:1.5rem;background:var(--daca-green-soft)}.drift-empty h3,.drift-empty p{margin:0}.drift-empty p{margin-top:.25rem;color:var(--daca-muted)}@media(max-width:760px){.drift-view>header{flex-direction:column}.drift-list article{grid-template-columns:1fr}.drift-actions{justify-items:start}}
  `],
})
export class MappingDriftComponent {
  readonly facade=inject(MappingDraftFacade);
  changes():readonly DriftChange[]{return this.facade.drift()?.changes??[];}
  brokenMappingId(change:DriftChange):string|null{return change.impactedMappingIds.find((id)=>this.facade.mappings().some((mapping)=>mapping.id===id&&mapping.status==='broken'))??null;}
  severityLabel(change:DriftChange):string{return change.severity==='breaking'?'Brechend':change.severity==='warning'?'Prüfen':'Information';}
  kindLabel(kind:DriftChange['kind']):string{return ({table_added:'Tabelle hinzugefügt',table_removed:'Tabelle entfernt',column_added:'Spalte hinzugefügt',column_removed:'Spalte entfernt',type_changed:'Datentyp geändert',length_changed:'Länge geändert',precision_changed:'Precision geändert',scale_changed:'Scale geändert',nullability_changed:'Nullability geändert',rename_candidate:'Umbenennungskandidat'} as const)[kind];}
  changeDescription(change:DriftChange):string{if(change.kind==='rename_candidate')return `Mögliche Umbenennung von „${change.previousValue??'–'}“ zu „${change.currentValue??'–'}“. Fachliche Bestätigung erforderlich.`;return `Vorher: ${change.previousValue??'–'} · Aktuell: ${change.currentValue??'–'}.`;}
  confidenceLabel(value:number|null):string{return value===null?'Konfidenz unbekannt':`${Math.round(value*100)} %`;}
}
