import { ChangeDetectionStrategy, Component, inject, input, output } from '@angular/core';
import { StatusBadgeComponent } from '@bit-daca/design-system';
import { MappingDraftFacade } from './mapping-draft.facade';
import { MappingStatus, MAPPING_STATUS_LABELS } from './data-models.models';

@Component({
  selector: 'daca-mapping-inspector', standalone: true, imports: [StatusBadgeComponent], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <aside class="mapping-inspector" aria-label="Detailinspektor">
      @if(showFieldSummary() && facade.selectedField();as field){<section><p class="daca-eyebrow">Feldmerkmale</p><h2>{{ field.name }}</h2><dl><div><dt>Geschäftsobjekt</dt><dd>{{ field.businessObject || 'Noch nicht zugeordnet' }}</dd></div><div><dt>Logische Entität</dt><dd>{{ field.entityName }}</dd></div><div><dt>Datentyp</dt><dd>{{ field.dataType }}{{ field.length?' ('+field.length+')':'' }}</dd></div><div><dt>Kardinalität</dt><dd>{{ field.minCount }}..{{ field.maxCount??'*' }} · {{ field.nullable?'Null erlaubt':'Pflichtfeld' }}</dd></div><div><dt>Klassifizierung</dt><dd>{{ field.classification }}</dd></div><div><dt>I14Y-Konzept</dt><dd>{{ field.conceptReferences[0]?.name || 'Nicht zugeordnet' }}</dd></div></dl></section>}
      @if(facade.selectedMapping();as mapping){<section class="mapping-detail"><div class="inspector-title"><div><p class="daca-eyebrow">Zuordnung</p><h2>{{ mapping.mappingType }}</h2></div><daca-status-badge [tone]="statusTone(mapping.status)">{{ statusLabel(mapping.status) }}</daca-status-badge></div><dl><div><dt>Logische Quellen</dt><dd>{{ sourceLabels(mapping.logicalFieldVersionIds) }}</dd></div><div><dt>Physische Ziele</dt><dd>{{ targetLabels(mapping.physicalColumnIds) }}</dd></div><div><dt>Klassifizierung</dt><dd>{{ mapping.classification }}</dd></div><div><dt>Verantwortlich</dt><dd>{{ mapping.responsibleName }}</dd></div><div><dt>Gültigkeit</dt><dd>{{ mapping.validFrom }} – {{ mapping.validTo||'offen' }}</dd></div><div><dt>Regel</dt><dd>{{ mapping.transformationRule||'Keine Transformation' }}</dd></div><div><dt>Kommentar</dt><dd>{{ mapping.comment||'–' }}</dd></div></dl>@if(mapping.validationResult?.issues?.length){<div class="validation-issues"><strong>Prüfergebnis</strong><ul>@for(issue of mapping.validationResult!.issues;track issue.code){<li [class.is-error]="issue.severity==='error'"><span>{{ issue.severity==='error'?'Fehler':'Hinweis' }}:</span> {{ issue.message }}</li>}</ul></div>}<div class="inspector-actions">@switch(mapping.status){@case('draft'){<button class="daca-button is-secondary" type="button" (click)="facade.openEdit(mapping.id,$event.currentTarget)">Bearbeiten</button><button class="daca-button" type="button" [disabled]="!canTransition(mapping.id)" (click)="submit.emit(mapping.id)">Zur Prüfung einreichen</button>}@case('review_pending'){<button class="daca-button" type="button" (click)="validate.emit(mapping.id)">Validieren</button>}@case('validated'){<button class="daca-button is-secondary" type="button" (click)="supersede.emit(mapping.id)">Ablösen</button>}@case('broken'){<button class="daca-button" type="button" (click)="facade.openBrokenResolution(mapping.id,$event.currentTarget)">Gegen Snapshot #{{ facade.snapshot()?.revision }} auflösen</button>}@case('superseded'){<p>Diese Zuordnung ist historisch und kann nicht mehr bearbeitet werden.</p>}}@if(mapping.status!=='superseded'){<button class="daca-button is-secondary" type="button" [disabled]="!canRemove() || (!canTransition(mapping.id) && !mapping.id.startsWith('draft-mapping-'))" (click)="remove.emit(mapping.id)">Verbindung entfernen</button>}</div></section>} @else {<section class="inspector-empty"><h2>Noch keine Zuordnung ausgewählt</h2><p>Wählen Sie ein Feld oder erstellen Sie über Graph, Matrix oder Dialog eine Zuordnung.</p></section>}
    </aside>
  `,
  styles: [`
    .mapping-inspector{display:grid;align-content:start;gap:1rem}.mapping-inspector>section{border:1px solid var(--daca-border);border-top:4px solid var(--daca-red);padding:1rem;background:#fff}.mapping-inspector h2{margin:.1rem 0 .8rem;font-size:1rem}.mapping-inspector dl{display:grid;gap:0;margin:0}.mapping-inspector dl div{display:grid;grid-template-columns:100px minmax(0,1fr);gap:.6rem;border-top:1px solid var(--daca-border);padding:.55rem 0}.mapping-inspector dt{color:var(--daca-muted);font-size:.59rem;font-weight:800;text-transform:uppercase}.mapping-inspector dd{margin:0;overflow-wrap:anywhere;font-size:.66rem;font-weight:700}.mapping-detail{border-top-color:var(--daca-blue)!important}.inspector-title{display:flex;align-items:start;justify-content:space-between;gap:.5rem}.validation-issues{margin-top:.8rem;border-left:4px solid var(--daca-orange);padding:.65rem;background:var(--daca-orange-soft);font-size:.66rem}.validation-issues ul{display:grid;gap:.35rem;margin:.4rem 0 0;padding-left:1rem}.validation-issues li.is-error{color:var(--daca-red-dark)}.inspector-actions{display:flex;flex-wrap:wrap;gap:.5rem;margin-top:1rem}.inspector-actions .daca-button{flex:1 1 8rem;padding-inline:.5rem}.inspector-actions p{margin:0;color:var(--daca-muted);font-size:.68rem}.inspector-empty p{color:var(--daca-muted);font-size:.72rem}@media(max-width:1199px){.mapping-inspector{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.mapping-inspector{grid-template-columns:1fr}}
  `],
})
export class MappingInspectorComponent {
  readonly facade=inject(MappingDraftFacade);readonly showFieldSummary=input(true);readonly canRemove=input(true);readonly validate=output<string>();readonly submit=output<string>();readonly supersede=output<string>();readonly remove=output<string>();
  sourceLabels(ids:string[]):string{return this.facade.logicalFields().filter((field)=>ids.includes(field.id)).map((field)=>field.name).join(', ')||ids.join(', ');}
  targetLabels(ids:string[]):string{return ids.map((id)=>this.facade.physicalColumns().find((column)=>column.id===id)?.qualifiedName??`Nicht im aktuellen Snapshot (${id})`).join(', ');}
  canTransition(id:string):boolean{return!id.startsWith('draft-mapping-')&&!this.facade.dirtyIds().has(id);}
  statusLabel(status:MappingStatus):string{return MAPPING_STATUS_LABELS[status];}
  statusTone(status:MappingStatus):'green'|'orange'|'red'|'neutral'{return ({validated:'green',review_pending:'orange',draft:'orange',broken:'red',superseded:'neutral'} as const)[status];}
}
