import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { StatusBadgeComponent } from '@bit-daca/design-system';
import { finalize, forkJoin } from 'rxjs';
import { CatalogApiService } from '../../core/catalog-api.service';
import { DataProduct, DomainAuditEvent, DomainSummary, GlossaryTermSummary } from '../../core/catalog.models';
import { DatePipe } from '@angular/common';
import dagre from '@dagrejs/dagre';

interface SemanticGraphNode { id: string; label: string; kind: 'domain' | 'product' | 'term' | 'label' | 'relation'; x: number; y: number }
interface SemanticGraphEdge { id: string; label: string; path: string }

@Component({selector:'daca-domain-detail',standalone:true,imports:[DatePipe,RouterLink,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
  <a routerLink="/domains">← Domänen &amp; Konzepte</a>
  @if (loading()) { <div class="daca-card detail-state">Domain wird geladen …</div> }
  @else if (error()) { <p class="daca-alert is-error" role="alert">{{ error() }}</p> }
  @else if (domain(); as item) {
    <section class="daca-page-heading"><div><p class="daca-eyebrow">Fachdomain · keine Organisation</p><h1>{{ item.preferredLabel }}</h1><p>{{ item.definition }}</p></div><div class="domain-heading-actions"><daca-status-badge [tone]="item.status === 'active' ? 'green' : 'neutral'">{{ item.status === 'active' ? 'Aktiv' : 'Stillgelegt' }}</daca-status-badge>@if(item.status === 'active'){<a class="daca-button is-secondary" routerLink="/glossary/proposals/new" [queryParams]="{domainId:item.id}">Term für diese Domain vorschlagen</a>}</div></section>
    <div class="detail-grid"><section class="daca-card"><div class="daca-card-header"><h2>Governance</h2><span>Revision {{ item.revision }}</span></div><div class="daca-card-body"><dl><div><dt>Data Owner</dt><dd><strong>{{ item.ownerName }}</strong><br>{{ item.ownerOrganization }}</dd></div><div><dt>Stellvertretung</dt><dd><strong>{{ item.deputyOwnerName }}</strong><br>{{ item.deputyOwnerOrganization }}</dd></div><div><dt>Stabile URI</dt><dd><code>{{ item.urn }}</code></dd></div></dl></div></section>
    <section class="daca-card"><div class="daca-card-header"><h2>Sprachlabels</h2></div><div class="daca-card-body">@for(label of item.labels;track label.language){<article><strong>{{ label.language.toUpperCase() }} · {{ label.preferredLabel }}</strong><p>{{ label.definition }}</p></article>}@empty{<p>Keine Sprachlabels erfasst.</p>}</div></section></div>
    <section class="daca-card relationship-card"><div class="daca-card-header"><div><p class="daca-eyebrow">Wissensgraph</p><h2>Beziehungen</h2></div><span>Domain → Produkte & Terme</span></div><div class="daca-card-body">
      @if(terms().length){<div class="domain-term-list" aria-label="Glossarterme dieser Domain">@for(term of terms();track term.id){<article><strong>{{term.preferredLabel}}</strong>@if(termAlternativeLabels(term);as alternatives){<span>Abkürzungen und alternative Labels: {{alternatives}}</span>}<p>{{term.definition}}</p></article>}</div>}
      @if(graphNodes().length>1){<div class="semantic-graph" role="img" [attr.aria-label]="'Wissensgraph der Domain '+item.preferredLabel+' mit '+products().length+' Produkten und '+terms().length+' Termen'" tabindex="0"><svg [attr.viewBox]="graphViewBox()" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><defs><marker id="semantic-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z"></path></marker></defs>@for(edge of graphEdges();track edge.id){<path class="graph-edge" [attr.d]="edge.path" marker-end="url(#semantic-arrow)"></path>}@for(node of graphNodes();track node.id){<g [attr.transform]="'translate('+(node.x-82)+','+(node.y-28)+')'" [attr.class]="'graph-node is-'+node.kind"><rect width="164" height="56" rx="5"></rect><text x="82" y="33" text-anchor="middle">{{shortLabel(node.label)}}</text></g>}</svg></div>}
      <div class="sr-only-graph"><h3>Beziehungen als Text</h3><p><strong>{{ item.preferredLabel }}</strong> enthält {{ products().length }} Datenprodukte und {{ terms().length }} Glossarterme.</p><ul>@for(product of products();track product.id){<li>Domain {{item.preferredLabel}} klassifiziert Produkt <a [routerLink]="['/products',product.id,'overview']">{{ product.title }}</a>.</li>}@for(term of terms();track term.id){<li>Domain {{item.preferredLabel}} verwaltet Term <strong>{{ term.preferredLabel }}</strong>@if(term.labels.length>1){ mit Labels {{ translatedLabels(term) }}.}@for(relation of term.relations;track relation.id){ Relation {{relation.relationType}} zu {{relation.targetLabel}}.}</li>}@empty{<li>Noch keine fachlichen Beziehungen.</li>}</ul></div>
      <details><summary>JSON-LD-Endpunkt</summary><code>/api/v1/knowledge-graph?domainId={{ item.id }}</code></details>
    </div></section>
    <section class="daca-card audit-card"><div class="daca-card-header"><div><p class="daca-eyebrow">Append-only</p><h2>Änderungsverlauf</h2></div><span>{{auditEvents().length}}</span></div><div class="daca-card-body">@if(auditEvents().length){<ol class="audit-list">@for(event of auditEvents();track event.id){<li><div><strong>{{auditAction(event.action)}}</strong><span>{{event.actor}} · @if(event.revision){Revision {{event.revision}} · }<time [attr.datetime]="event.occurredAt">{{event.occurredAt|date:'dd.MM.yyyy, HH:mm'}}</time></span></div></li>}</ol>}@else{<p>Noch keine protokollierten Domain-Änderungen.</p>}</div></section>
  }
`,styles:[`.detail-state{padding:2rem;margin-top:1rem}.domain-heading-actions{display:flex;align-items:flex-end;flex-direction:column;gap:.75rem}.detail-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(19rem,1fr));gap:1rem}.detail-grid dl{display:grid;gap:1rem}.detail-grid dl div{display:grid;grid-template-columns:8rem 1fr}.detail-grid dd{margin:0}.relationship-card,.audit-card{margin-top:1rem}.relationship-card li{margin:.5rem 0;overflow-wrap:anywhere}.domain-term-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(16rem,1fr));gap:.75rem;margin-bottom:1rem}.domain-term-list article{padding:.75rem;border:1px solid #d6dade;background:#fff}.domain-term-list article>*{display:block}.domain-term-list span{margin-top:.25rem;color:#4f5962;font-size:.82rem}.domain-term-list p{margin:.45rem 0 0}.semantic-graph{overflow:auto;min-height:22rem;border:1px solid #d6dade;background:#f8fafb}.semantic-graph:focus{outline:3px solid #006699;outline-offset:2px}.semantic-graph svg{display:block;width:100%;min-width:44rem;height:28rem}.graph-edge{fill:none;stroke:#78838d;stroke-width:2}.graph-edge+text{fill:#48525b}.graph-node rect{fill:#fff;stroke:#68737d;stroke-width:1.5}.graph-node.is-domain rect{fill:#e1001a;stroke:#a80014}.graph-node.is-domain text{fill:#fff}.graph-node.is-term rect{fill:#e7f2f7;stroke:#006699}.graph-node.is-product rect{fill:#f7efe0;stroke:#9b6300}.graph-node.is-label rect,.graph-node.is-relation rect{fill:#f1edf7;stroke:#64458a}.graph-node text{font-size:12px;font-weight:700}.sr-only-graph{margin-top:1rem}.audit-list{list-style:none;padding:0}.audit-list li{padding:.75rem 0;border-bottom:1px solid #d6dade}.audit-list li div{display:grid}.audit-list span{color:#5b636b}@media(max-width:700px){.domain-heading-actions{align-items:flex-start}.detail-grid dl div{grid-template-columns:1fr}}`]})
export class DomainDetailComponent {
  private readonly api=inject(CatalogApiService); private readonly route=inject(ActivatedRoute); readonly domain=signal<DomainSummary|null>(null); readonly products=signal<readonly DataProduct[]>([]); readonly terms=signal<readonly GlossaryTermSummary[]>([]);readonly auditEvents=signal<readonly DomainAuditEvent[]>([]); readonly loading=signal(true); readonly error=signal('');
  readonly graphLayout=computed(()=>this.layoutGraph()); readonly graphNodes=computed(()=>this.graphLayout().nodes);readonly graphEdges=computed(()=>this.graphLayout().edges);readonly graphViewBox=computed(()=>`0 0 ${this.graphLayout().width} ${this.graphLayout().height}`);
  constructor(){const id=this.route.snapshot.paramMap.get('id')??'';forkJoin({domain:this.api.loadDomain(id),products:this.api.loadDataProductsForDomain(id),terms:this.api.loadGlossaryTerms([id]),auditEvents:this.api.loadDomainAuditEvents(id)}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:({domain,products,terms,auditEvents})=>{this.domain.set(domain);this.products.set(products);this.terms.set(terms);this.auditEvents.set(auditEvents);},error:()=>this.error.set('Die Domain konnte nicht vollständig geladen werden.')});}
  translatedLabels(term:GlossaryTermSummary):string{return term.labels.map((label)=>`${label.language.toUpperCase()}: ${label.preferredLabel}${label.alternativeLabels.length?` (auch: ${label.alternativeLabels.join(', ')})`:''}`).join(' · ');}
  termAlternativeLabels(term:GlossaryTermSummary):string{return term.labels.flatMap((label)=>label.alternativeLabels.map((alternative)=>`${label.language.toUpperCase()}: ${alternative}`)).join(' · ');}
  shortLabel(value:string):string{return value.length>25?`${value.slice(0,24)}…`:value;}
  auditAction(value:string):string{return({'created':'Domain erstellt','updated':'Domain geändert','retired':'Domain stillgelegt','approved':'Antrag genehmigt'} as Record<string,string>)[value]??value;}
  private layoutGraph():{nodes:SemanticGraphNode[];edges:SemanticGraphEdge[];width:number;height:number}{const domain=this.domain();if(!domain)return{nodes:[],edges:[],width:900,height:420};const nodes:Array<Omit<SemanticGraphNode,'x'|'y'>>=[{id:`domain:${domain.id}`,label:domain.preferredLabel,kind:'domain'}];const edges:Array<{id:string;source:string;target:string;label:string}>=[];for(const product of this.products()){const id=`product:${product.id}`;nodes.push({id,label:product.title,kind:'product'});edges.push({id:`domain-product:${product.id}`,source:`domain:${domain.id}`,target:id,label:'dcat:theme'});}for(const term of this.terms()){const termId=`term:${term.id}`;nodes.push({id:termId,label:term.preferredLabel,kind:'term'});edges.push({id:`domain-term:${term.id}`,source:`domain:${domain.id}`,target:termId,label:'skos:inScheme'});for(const label of term.labels){const id=`label:${term.id}:${label.language}`;nodes.push({id,label:`${label.language.toUpperCase()}: ${label.preferredLabel}`,kind:'label'});edges.push({id:`term-label:${term.id}:${label.language}`,source:termId,target:id,label:'prefLabel'});}for(const relation of term.relations){const id=`relation:${term.id}:${relation.id}`;nodes.push({id,label:relation.targetLabel,kind:'relation'});edges.push({id:`term-relation:${term.id}:${relation.id}`,source:termId,target:id,label:relation.relationType});}}const graph=new dagre.graphlib.Graph();graph.setGraph({rankdir:'LR',nodesep:24,ranksep:80,marginx:35,marginy:35});graph.setDefaultEdgeLabel(()=>({}));for(const node of nodes)graph.setNode(node.id,{width:164,height:56});for(const edge of edges)graph.setEdge(edge.source,edge.target,{id:edge.id});dagre.layout(graph);const positioned=nodes.map((node)=>({...node,...graph.node(node.id) as {x:number;y:number}}));const paths=edges.map((edge)=>{const layout=graph.edge(edge.source,edge.target) as {points:Array<{x:number;y:number}>};return{id:edge.id,label:edge.label,path:layout.points.map((point,index)=>`${index?'L':'M'} ${point.x} ${point.y}`).join(' ')}});const dimensions=graph.graph() as {width?:number;height?:number};return{nodes:positioned,edges:paths,width:Math.max(700,dimensions.width??700),height:Math.max(420,dimensions.height??420)};}
}
