import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { StatusBadgeComponent } from '@bit-daca/design-system';
import { finalize } from 'rxjs';
import { CatalogApiService } from '../../core/catalog-api.service';
import { DomainGlossaryFixtureState } from '../../core/catalog.models';

@Component({selector:'daca-domain-glossary-fixture',standalone:true,imports:[FormsModule,RouterLink,StatusBadgeComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
  <a routerLink="/poc-simulation">← PoC-Simulationen</a><section class="daca-page-heading"><div><p class="daca-eyebrow">Journeys 08 & 09</p><h1>Domäne und Terminology vorbereiten</h1><p>Diese Fixture verwaltet ausschliesslich das synthetische Fahrzeugprodukt und die dafür erzeugten Governance-Artefakte.</p></div>@if(fixture();as item){<daca-status-badge [tone]="item.state==='completed'?'green':item.state==='notPrepared'?'neutral':'orange'">{{stateLabel(item.state)}}</daca-status-badge>}</section>
  @if(error()){<p class="daca-alert is-error" role="alert">{{error()}}</p>}@if(notice()){<p class="daca-alert" role="status">{{notice()}}</p>}
  @if(loading()){<div class="daca-card fixture-state">Fixture-Status wird geladen …</div>}@else if(fixture();as item){<div class="fixture-grid"><section class="daca-card"><div class="daca-card-header"><h2>Deterministischer Zustand</h2></div><div class="daca-card-body"><dl><div><dt>Produkt</dt><dd>{{item.productTitle||'Noch nicht vorbereitet'}}</dd></div><div><dt>Domains</dt><dd>{{item.domainIds.length}}</dd></div><div><dt>Offene Domain-Anträge</dt><dd>{{item.openDomainRequestCount}}</dd></div><div><dt>Offene Termvorschläge</dt><dd>{{item.openTermProposalCount}}</dd></div></dl><button class="daca-button" type="button" [disabled]="busy()" (click)="prepare()">Fixture vorbereiten</button></div></section><section class="daca-card"><div class="daca-card-header"><h2>Journey starten</h2></div><div class="daca-card-body fixture-links"><a class="daca-button" routerLink="/poc-guide/domain-governance">Journey 08 öffnen</a><a class="daca-button is-secondary" routerLink="/poc-guide/glossary-governance">Journey 09 öffnen</a><a routerLink="/domains">Domäne und Terminology</a>@if(item.productId){<a [routerLink]="['/products',item.productId,'metadata']">Fahrzeugprodukt bearbeiten</a>}</div></section></div>
  <section class="daca-card fixture-reset"><div class="daca-card-header"><h2>Fixture zurücksetzen</h2></div><div class="daca-card-body"><p>Der Reset betrifft nur synthetische Journey-Artefakte. Geben Sie zur Bestätigung <strong>DOMAIN-GLOSSARY</strong> ein.</p><label>Bestätigung<input [(ngModel)]="confirmation" autocomplete="off"></label><button class="daca-button is-secondary" type="button" [disabled]="busy()||confirmation!=='DOMAIN-GLOSSARY'" (click)="reset()">Synthetische Fixture zurücksetzen</button></div></section>}
`,styles:[`.fixture-state{padding:2rem}.fixture-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(20rem,1fr));gap:1rem}.fixture-grid dl{display:grid;gap:.75rem}.fixture-grid dl div{display:grid;grid-template-columns:12rem 1fr}.fixture-grid dd{margin:0}.fixture-links{display:grid;gap:.75rem;align-content:start}.fixture-reset{margin-top:1rem}.fixture-reset label{display:grid;gap:.35rem;max-width:20rem;margin:1rem 0}`]})
export class DomainGlossaryFixtureComponent {private readonly api=inject(CatalogApiService);readonly fixture=signal<DomainGlossaryFixtureState|null>(null);readonly loading=signal(true);readonly busy=signal(false);readonly error=signal('');readonly notice=signal('');confirmation='';constructor(){this.load();}load():void{this.loading.set(true);this.api.loadDomainGlossaryFixture().pipe(finalize(()=>this.loading.set(false))).subscribe({next:(item)=>this.fixture.set(item),error:()=>this.error.set('Die Domain-/Glossar-Fixture ist in dieser Umgebung nicht verfügbar.')});}prepare():void{this.busy.set(true);this.error.set('');this.api.prepareDomainGlossaryFixture().pipe(finalize(()=>this.busy.set(false))).subscribe({next:(item)=>{this.fixture.set(item);this.notice.set('Die synthetische Fixture ist für Journey 08 vorbereitet.');},error:(error)=>this.error.set(error?.error?.detail??'Die Fixture konnte nicht vorbereitet werden.')});}reset():void{if(this.confirmation!=='DOMAIN-GLOSSARY')return;this.busy.set(true);this.api.resetDomainGlossaryFixture(this.confirmation).pipe(finalize(()=>this.busy.set(false))).subscribe({next:(item)=>{this.fixture.set(item);this.confirmation='';this.notice.set('Die synthetischen Domain-/Glossar-Artefakte wurden zurückgesetzt.');},error:(error)=>this.error.set(error?.error?.detail??'Die Fixture konnte nicht zurückgesetzt werden.')});}stateLabel(state:DomainGlossaryFixtureState['state']):string{return({notPrepared:'Nicht vorbereitet',ready:'Bereit',domainPending:'Domain-Antrag offen',domainApproved:'Domain genehmigt',termPending:'Termreview offen',completed:'Abgeschlossen'})[state];}}
