import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { UserPreferencesService } from '../../core/user-preferences.service';
import { GlossaryWordComponent } from './glossary-word.component';

type Copy = readonly [string, string, string, string];

@Component({
  selector: 'daca-documentation-static',
  standalone: true,
  imports: [RouterLink, GlossaryWordComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav class="documentation-breadcrumb" [attr.aria-label]="tr(['Brotkrümelnavigation', 'Fil d’Ariane', 'Percorso di navigazione', 'Breadcrumb'])"><a routerLink="/documentation">{{ tr(['Dokumentation Datenkatalog', 'Documentation du catalogue', 'Documentazione del catalogo', 'Catalog documentation']) }}</a><span>›</span><span>{{ tr(['Statische Dokumentation', 'Documentation statique', 'Documentazione statica', 'Static documentation']) }}</span></nav>
    <section class="daca-page-heading"><div><p class="daca-eyebrow">Data Catalog</p><h1>{{ tr(['Statische Dokumentation', 'Documentation statique', 'Documentazione statica', 'Static documentation']) }}</h1><p>{{ tr(['Die wichtigsten fachlichen und technischen Grundlagen der lokalen DaCa-Vorschau.', 'Les principes métier et techniques de l’aperçu local de DaCa.', 'I principi funzionali e tecnici dell’anteprima locale di DaCa.', 'Core business and technical concepts of the local DaCa preview.']) }}</p></div></section>
    <div class="documentation-articles">
      <article><div class="article-meta"><span>Kategorie: Grundlagen</span><span>Tags: DaCa, Katalog</span><time datetime="2026-09-24">Erstellt: 24.09.2026</time></div><p class="daca-eyebrow">01 · Katalog</p><h2>{{ tr(['Was ist DaCa?', 'Qu’est-ce que DaCa ?', 'Che cos'è DaCa?', 'What is DaCa?']) }}</h2><p>{{ tr(['DaCa ist der zentrale Datenkatalog der Data Platform BIT. Er verwaltet Metadaten, Datenprodukte, Endpunkte, Herkunftsinformationen und Zugriffsregeln an einem Ort.', 'DaCa est le catalogue de données central de la plateforme de données de l’OFIT. Il gère les métadonnées, les produits de données, les points d’accès, la provenance et les règles d’accès en un seul endroit.', 'DaCa è il catalogo dati centrale della piattaforma dati dell’UFIT. Gestisce metadati, prodotti dati, endpoint, provenienza e regole di accesso in un unico luogo.', 'DaCa is the central data catalog of the BIT data platform. It manages metadata, data products, endpoints, provenance and access rules in one place.']) }}</p></article>
      <article><div class="article-meta"><span>Kategorie: Governance</span><span>Tags: Rollen, Data Owner, Data Steward</span><time datetime="2026-09-24">Erstellt: 24.09.2026</time></div><p class="daca-eyebrow">02 · {{ tr(['Verantwortung', 'Responsabilité', 'Responsabilità', 'Responsibility']) }}</p><h2>{{ tr(['Rollen und Zuständigkeiten', 'Rôles et responsabilités', 'Ruoli e responsabilità', 'Roles and responsibilities']) }}</h2><p><daca-glossary-word lookup="Data Owner" [label]="tr(['Data Owner', 'Data Owner', 'Data Owner', 'Data Owner'])" /> {{ tr(['tragen die fachliche Verantwortung für konkrete Domänen, Modelle oder Datenprodukte.', 'assument la responsabilité métier de domaines, modèles ou produits précis.', 'sono responsabili di domini, modelli o prodotti specifici.', 'are accountable for specific domains, models or products.']) }} <daca-glossary-word lookup="Data Steward" label="Data Steward" /> {{ tr(['pflegen Modelle und Metadaten in ihrem zugewiesenen Bereich. Eine organisatorische Rolle und eine direkte Objektzuordnung werden in der Zuständigkeitsansicht getrennt sichtbar.', 'gèrent les modèles et métadonnées de leur périmètre. La vue des responsabilités distingue les rôles organisationnels des attributions directes.', 'curano modelli e metadati nel proprio ambito. La vista distingue ruoli organizzativi e assegnazioni dirette.', 'maintain models and metadata in their scope. The responsibility view distinguishes organizational roles from direct object assignments.']) }}</p><a routerLink="/settings/responsibilities">{{ tr(['Zuständigkeiten ansehen', 'Voir les responsabilités', 'Vedi responsabilità', 'View responsibilities']) }} →</a><br><a routerLink="/settings/role-changes">{{ tr(['Rollenprotokoll lesen', 'Lire le journal des rôles', 'Leggi il registro dei ruoli', 'Read role protocol']) }} →</a></article>
      <article><div class="article-meta"><span>Kategorie: Modellierung</span><span>Tags: Logisches Modell, Physische Repräsentation</span><time datetime="2026-09-24">Erstellt: 24.09.2026</time></div><p class="daca-eyebrow">03 · {{ tr(['Datenstruktur', 'Structure', 'Struttura', 'Structure']) }}</p><h2>{{ tr(['Modelle und Repräsentationen', 'Modèles et représentations', 'Modelli e rappresentazioni', 'Models and representations']) }}</h2><p><daca-glossary-word lookup="Logisches Modell" [label]="tr(['Logische Modelle', 'Modèles logiques', 'Modelli logici', 'Logical models'])" /> {{ tr(['beschreiben fachliche Entitäten und Felder. Eine', 'décrivent les entités et champs métier. Une', 'descrivono entità e campi funzionali. Una', 'describe business entities and fields. A']) }} <daca-glossary-word lookup="Physische Repräsentation" [label]="tr(['physische Repräsentation', 'représentation physique', 'rappresentazione fisica', 'physical representation'])" /> {{ tr(['ist die technische Struktur, etwa eine Tabelle. Das Mapping verbindet beide Ebenen versioniert.', 'est une structure technique, par exemple une table. Le mappage relie les deux niveaux avec versionnement.', 'è una struttura tecnica, per esempio una tabella. Il mapping collega i due livelli con versioni.', 'is a technical structure, such as a table. Versioned mappings connect both levels.']) }}</p><a routerLink="/models">{{ tr(['Datenmodelle öffnen', 'Ouvrir les modèles', 'Apri modelli', 'Open models']) }} →</a></article>
      <article><div class="article-meta"><span>Kategorie: Zugriff</span><span>Tags: Datenprodukt, Freigabe</span><time datetime="2026-09-24">Erstellt: 24.09.2026</time></div><p class="daca-eyebrow">04 · {{ tr(['Zugriff', 'Accès', 'Accesso', 'Access']) }}</p><h2>{{ tr(['Datenprodukte und Freigaben', 'Produits et autorisations', 'Prodotti e autorizzazioni', 'Products and access']) }}</h2><p>{{ tr(['Ein Datenprodukt verbindet Beschreibung, Verantwortlichkeit, Qualität und Endpunkte. Zugriffe werden nur nach einer gültigen Richtlinie gewährt. Die lokale Vorschau verwendet synthetische Daten und zeigt die einzelnen Freigabeschritte nachvollziehbar.', 'Un produit relie description, responsabilité, qualité et points d’accès. L’accès dépend d’une politique valide.', 'Un prodotto collega descrizione, responsabilità, qualità ed endpoint. L’accesso richiede una politica valida.', 'A data product links its description, ownership, quality and endpoints. Access requires a valid policy.']) }}</p><a routerLink="/documentation/journeys">{{ tr(['Abläufe Schritt für Schritt', 'Voir les parcours', 'Vedi i percorsi', 'View step-by-step journeys']) }} →</a></article>
      <article id="mapping-inkonsistenz">
        <div class="article-meta"><span>Kategorie: Modellierung und Datenqualität</span><span>Tags: Mapping, Inkonsistenzfehler, Data Owner, Data Steward</span><time datetime="2026-09-24">Erstellt: 24.09.2026</time></div>
        <p class="daca-eyebrow">05 · Modellqualität</p>
        <h2>Unverbundene logische Felder bearbeiten</h2>
        <p>Ein logisches Modell kann ohne physische Repräsentation erstellt werden. Sobald es eine physische Bindung hat, prüft DaCa seine Felder auf einen physischen Counterpart. Eine Verbindung kann im Mapping-Arbeitsplatz entfernt werden; ein logisches Feld kann im rechten Merkmalsbereich entfernt werden. Der Entwurf bleibt speicherbar, auch wenn dabei eine Zuordnung fehlt.</p>
        <p>Ein unverbundenes Feld erscheint als <strong>Inkonsistenzfehler</strong>. Der Data Owner erhält eine Aufgabe und muss den Befund mit Begründung akzeptieren oder einen Data Steward mit der Prüfung beauftragen. Eine Annahme dokumentiert den Entscheid, beseitigt den Qualitätsfehler aber nicht. Der beauftragte Data Steward erhält eine eigene Aufgabe. Wird das Feld wieder verbunden oder aus dem Modell entfernt, löst DaCa den Vorgang und die offenen Aufgaben automatisch auf. Modell- und Mappingversionen bleiben nachvollziehbar.</p>
        <div class="article-images"><figure><img src="/assets/docs/mapping-workspace-compact.png" alt="Kompakter Mappinggraph mit Feldmerkmalen im rechten Editor" loading="lazy"><figcaption>Die kompakte Grafik lässt den Merkmalseditor rechts sichtbar.</figcaption></figure><figure><img src="/assets/docs/mapping-inconsistency-owner.png" alt="Inkonsistenzfehler mit Entscheidmöglichkeiten für den Data Owner" loading="lazy"><figcaption>Der Data Owner akzeptiert den Fehler oder beauftragt einen Data Steward.</figcaption></figure></div>
        <a routerLink="/documentation/journeys/resolve-logical-mapping-inconsistency">Journey zum Inkonsistenzfall öffnen →</a>
      </article>
    </div>
  `,
  styles: [`
    .documentation-breadcrumb{display:flex;align-items:center;gap:10px;margin-bottom:20px;color:var(--daca-muted);font-size:.78rem}.documentation-breadcrumb a,.documentation-articles a{color:var(--daca-blue)}.documentation-articles{display:grid;gap:18px;max-width:1100px}.documentation-articles article{border:1px solid var(--daca-border);border-left:4px solid var(--daca-blue);padding:22px 26px;background:var(--daca-surface)}.documentation-articles h2{margin:8px 0 11px;font-size:1.24rem}.documentation-articles p:not(.daca-eyebrow){max-width:85ch;margin:0 0 13px;color:var(--daca-muted);line-height:1.6}.documentation-articles a{font-size:.83rem;font-weight:750}.article-meta{display:flex;flex-wrap:wrap;gap:.45rem 1rem;margin-bottom:.6rem;color:var(--daca-muted);font-size:.61rem}.article-meta span,.article-meta time{border:1px solid var(--daca-border);padding:.2rem .4rem}.article-images{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;margin:1rem 0}.article-images figure{margin:0;border:1px solid var(--daca-border);background:var(--daca-surface)}.article-images img{display:block;width:100%;height:auto;aspect-ratio:16/9;object-fit:contain;object-position:top}.article-images figcaption{padding:.45rem .6rem;color:var(--daca-muted);font-size:.63rem}@media(max-width:760px){.article-images{grid-template-columns:1fr}}
  `],
})
export class DocumentationStaticComponent {
  private readonly preferences = inject(UserPreferencesService);
  tr(copy: Copy): string { return copy[({ de: 0, fr: 1, it: 2, en: 3 })[this.preferences.language()]]; }
}
